<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Daily Expense Invoice</title>
  <style>
    @page { margin: 20px; } /* ✅ Add safe margin */
    body { font-family: sans-serif; -webkit-print-color-adjust: exact; }

    .header, .footer { text-align: center; }
    .header h1 { margin: 0; font-size: 18px; text-transform: uppercase; }
    .header p { margin: 2px 0; font-size: 12px; }
    .divider { border-bottom: 1px dashed #000; margin: 8px 0; }

    table { width: 100%; border-collapse: collapse; font-size: 12px; }
    th, td { border: 1px solid #000; padding: 4px; text-align: center; }
    th { background: #f0f0f0; }

    .summary { margin-top: 8px; text-align: right; font-weight: bold; }
    .no-print { display: none; }
  </style>
</head>
<body>
  <div style="padding: 15px;"> <!-- ✅ Wrapper with padding -->

    <div class="header">
      <h1>Inoodex Inventory</h1>
      <p>Daily Expense Report</p>
      @if($request->from && $request->to)
        <p style="font-size:11px;">
          From: {{ \Carbon\Carbon::parse($request->from)->format('d M, Y') }}
          — To: {{ \Carbon\Carbon::parse($request->to)->format('d M, Y') }}
        </p>
      @endif
      <p style="font-size:11px;">Generated: {{ now()->format('d M, Y g:i A') }}</p>
    </div>

    <div class="divider"></div>

    <table>
      <thead>
        <tr>
          <th>#</th>
          <th>Date</th>
          <th>Category</th>
          <th>Remarks</th>
          <th>Amount</th>
          <th>Spend Method</th>
        </tr>
      </thead>
      <tbody>
        @foreach($dailyExpense as $i => $exp)
        <tr>
          <td>{{ $i+1 }}</td>
          <td>{{ \Carbon\Carbon::parse($exp->date)->format('d M, Y') }}</td>
          <td>{{ $exp->category_name }}</td>
          <td>{{ $exp->remarks }}</td>
          <td>${{ number_format($exp->amount, 2) }}</td>
          <td>{{ ucfirst(str_replace('_', ' ', $exp->spend_method)) }}</td>
        </tr>
        @endforeach
        <tr>
          <td colspan="4" style="text-align:right;font-weight:bold;">Total</td>
          <td style="font-weight:bold;">${{ number_format($dailyExpense->sum('amount'),2) }}</td>
          <td></td>
        </tr>
      </tbody>
    </table>

    <div class="divider"></div>

    <div class="footer">
      <p style="font-size:10px;">Generated by: {{ auth()->user()->name }}</p>
    </div>

  </div>

  <script>
    window.print();
  </script>
</body>
</html>
